future4code/cruz-labe-food7

package-lock.json
package.json
public/index.html
src/App.js
src/components/Alert.js
src/components/Loader.js
src/constants/colors.js
src/constants/theme.js
src/constants/urls.js
src/global/GlobalState.js
src/global/GlobalStateContext.js
src/hooks/useForm.js
src/hooks/useInput.js
src/hooks/useProtectedPage.js
src/hooks/useRequestData.js
src/hooks/useUnprotectedPage.js
src/pages/CartPage/CartPage.js
src/pages/ErrorPage/ErrorPage.js
src/pages/HomePage/HomePage.js
src/pages/LoginPage/LoginPage.js
src/pages/ProfilePage/ProfilePage.js
src/pages/RestaurantPage/RestaurantPage.js
src/pages/SignUpPage/SignUpPage.js
src/routes/Router.js
src/routes/coordinator.js

router, global state, cores

---

src/components/RestaurantCard/RestaurantCard.js
src/constants/urls.js
src/global/GlobalState.js
src/pages/HomePage/HomePage.js

começo cards restaurantes

---

src/hooks/useProtectedPage.js
src/pages/AddressPage/AddressPage.js
src/pages/HomePage/HomePage.js
src/pages/LoginPage/LoginPage.js
src/pages/SignUpPage/SignUpPage.js

arrumei urls

---

src/components/RestaurantCard.js/RestaurantCardDetails.js
src/components/RestaurantCard.js/styled.js
src/components/RestaurantCard/RestaurantCard.js
src/hooks/useProtectedPage.js
src/pages/HomePage/HomePage.js
src/pages/RestaurantPage/RestaurantPage.js
src/routes/coordinator.js

segue o pr que liga a home com o detalhes do restaurante por parms. esta funcionando ok, segue foto.
Preciso que resolvam o conflito antes de aprovar. Foi necessário ajustar a função no history, passando o id.

pasando parms home para detalhes do rest.

---

src/components/RestaurantCard.js/RestaurantCardDetails.js
src/components/RestaurantCard.js/styled.js
src/components/RestaurantCard/RestaurantCard.js
src/hooks/useProtectedPage.js
src/pages/HomePage/HomePage.js
src/pages/RestaurantPage/RestaurantPage.js
src/routes/coordinator.js

Revert "pasando parms home para detalhes do rest."

---

src/components/RestaurantCard.js/ProductCard.js
src/components/RestaurantCard.js/styled.js
src/hooks/useProtectedPage.js

Lanes details restaurant

---

src/components/CategoryCard/CategoryCard.js
src/global/GlobalState.js
src/pages/HomePage/HomePage.js

homepage com filtros

---

src/components/RestaurantCard/RestaurantCard.js
src/pages/HomePage/HomePage.js
src/pages/RestaurantPage/RestaurantPage.js
src/routes/coordinator.js

params ok - lista de rest para detalhes

---

src/components/CategoryCard/CategoryCard.js
src/pages/HomePage/HomePage.js

categorias funcionando

---

src/components/RestaurantCard.js/ProductCard.js
src/components/RestaurantCard.js/styled.js
src/pages/RestaurantPage/RestaurantPage.js
src/pages/RestaurantPage/SelectProductTocard.js
src/pages/RestaurantPage/styled.js

ajuste estilo rest detalhes. retirada de borda

---

src/global/GlobalState.js
src/pages/CartPage/CartPage.js

iniciei página de carrinho

---

src/components/RestaurantCard.js/ProductCard.js
src/components/RestaurantCard.js/styled.js
src/components/RestaurantCard/RestaurantCard.js
src/pages/AddressPage/AddressPage.js
src/pages/LoginPage/LoginPage.js
src/pages/SignUpPage/SignUpPage.js

estilizacao

---

src/pages/CartPage/CartPage.js
src/pages/CartPage/styled.js

layout carrinho concluido

---

src/components/OrdersHistoryCard/ordersCard.js
src/pages/HomePage/HomePage.js
src/pages/ProfilePage/ProfilePage.js
src/pages/ProfilePage/styled.js

estilizando card de historico

---

src/pages/CartPage/CartPage.js
src/pages/CartPage/components/AddressBox.js
src/pages/CartPage/components/Payment.js
src/pages/CartPage/components/ProductCart.js
src/pages/CartPage/components/RestaurantDetails.js
src/pages/CartPage/components/Total.js
src/pages/CartPage/index.js
src/pages/CartPage/styled.js

organizei os componentes

---

src/components/Footer.js

rotas footer

---

src/pages/ProfilePage/ProfilePage.js

criando condicional nas orders

---

src/components/Header.js
src/global/GlobalState.js
src/pages/RestaurantPage/RestaurantPage.js

categorias pratos restaurantes

---

src/pages/EditAddressPage/EditAddress.js
src/pages/EditAddressPage/styled.js
src/pages/EditProfilePage/EditProfile.js
src/pages/EditProfilePage/styled.js
src/pages/ProfilePage/ProfilePage.js

organizando codigo e tirando console.logs

---

src/components/CategoryCard/CategoryCard.js
src/components/Footer.js
src/components/Header.js
src/pages/EditAddressPage/EditAddress.js
src/pages/EditProfilePage/EditProfile.js
src/pages/HomePage/HomePage.js
src/pages/ProfilePage/ProfilePage.js
src/pages/RestaurantPage/RemoveProducts.js

footer colorido pagina atual

---

src/global/GlobalState.js
src/pages/ProfilePage/ProfilePage.js

arrumando problema do map em orders

---

src/components/Header.js
src/components/RestaurantCard.js/ProductCard.js
src/components/RestaurantCard.js/RestaurantCardDetails.js
src/global/GlobalState.js
src/pages/EditAddressPage/EditAddress.js
src/pages/EditProfilePage/EditProfile.js
src/pages/HomePage/HomePage.js
src/pages/ProfilePage/ProfilePage.js
src/pages/RestaurantPage/RemoveProducts.js
src/pages/RestaurantPage/RestaurantPage.js
src/pages/RestaurantPage/SelectProductTocard.js
src/pages/SignUpPage/SignUpPage.js

limpada console

---

src/global/GlobalState.js
src/pages/RestaurantPage/RestaurantPage.js
src/pages/RestaurantPage/SelectProductTocard.js
src/pages/RestaurantPage/clearcart.js

card esvaziar carrinho

---

src/pages/RestaurantPage/SelectProductTocard.js

arrumei card
